### ISSUE TITLE
Exception: The argument is not initialized or iterable()

### ISSUE THREAD

**Issue by Surt** [snowair/phalcon-debugbar#1]
Hi,

I was triying to setup the debugbar with the Phalcon 2.0 release, it throws a 
Exception: The argument is not initialized or iterable() phalcon/http/response/headers.zep (98)

Can't find the error line that throws the exception from debugbar, it appears to be after the 
$debugbar->modifyResponse($response); but can't follow it after that.

**Comment by snowair** [comment]
Think you, I will  improve it compatible with Phalcon 2.

**Comment by snowair** [comment]
now you can update

**Comment by Surt** [comment]
Hi @snowair,

great! I'm triying to make it work now.
it seems to work right at the moment, except for something related to the assetsController not found. The debug bar is not show on pages.
let me paste the warnings here:

each asset returns the same as content: 
MyModuleNamespaceHere\AssetController handler class cannot be loaded

they are transfered as text/html since the content is the error from above.

Uncaught ReferenceError: PhpDebugBar is not defined(anonymous function) @ (index):441
(index):438 Resource interpreted as Script but transferred with MIME type text/html: "http://route/_debugbar/assets/javascript".
(index):437 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://route/_debugbar/assets/stylesheets".

Edited: It seems that the error is produced by my router wich replaces the namespace. Will try to fix it and update this post.

**Comment by Surt** [comment]
Works like a charm. Still triying to make the timeline and session collectors works.
Thank you @snowair
