### ISSUE TITLE
No query, cache etc. tabs

### ISSUE THREAD

**Issue by Klinir** [snowair/phalcon-debugbar#15]
Hi,
For some reason can't find these tabs. 
Messages, exceptions, timeline, request tabs are shown. And pushing texts are working like charm.

I use Phalcon 2.1.0 Beta 2, but also tried downgrade to 2.0.3 and was same issue.

**Comment by snowair** [comment]
Others are disabled by default. You should enable them in the debugbar config file.

Please read the reamdme.md
