### ISSUE TITLE
Incorrect asset URI rendered

### ISSUE THREAD

**Issue by njoyard** [snowair/phalcon-debugbar#16]
Since commit 95efd03cad7ec92c836cbabc7dd5bdec9303b1dd phalcon-debugbar always renders root asset URIs (ie. `/_debugbar/assets...`) instead of using the application baseUri.

This disallows using phalcon-debugbar on any application that is not hosted at the root of its domain.

Contrary to what the commit message seems to indicate, it _did_ work perfectly before. IMO it should be reverted, I think @bluetec had a configuration issue that had nothing to do with phalcon-debugbar itself.

**Comment by snowair** [comment]
I strongly suggest everyone to assign a host domain to your  document root, and set the baseUri of uri service to `/`. 

This is because it is diffcult to config nginx for phalcon-app having a baseUri. ( I didn't  know much about nginx.)

But if someone can write a nginx config file that support baseUri well, I agree with you commit 95efd should be reverted.

**Comment by njoyard** [comment]
Uh... I don't think I get it.

It's very easy for any other webserver. Just put your app in `documentRoot/path/to/app` and set baseUri in url service to `path/to/app`. That's it. I don't see how that'd be different for nginx.

But having phalcon-debugbar temporarily force the baseUri to `/` when rendering its assets just makes no sense. What if I want to host several apps on the same domain?

IMO it would just be easier for everyone to revert 95efd03, which would make the general use case work again, and then work around the specific issue that commit was intended to solve. Or _at the very least_ make that optional.

**Comment by njoyard** [comment]
Just to be clearer on my point here : phalcon-debugbar, when installed, becomes _part of_ the app. There's no sense to me to giving it a different baseUri when rendering.

**Comment by snowair** [comment]
Yes, I agree with you and I had reverted it.

**Comment by ghost** [comment]
@njoyard @snowair 
1. in my case, i use multi module application, a module for front-end `http://foo.bar` and a module for back-end `http://foo.bar/admin`.
2. Phalcon debugbar routes assets only match with `{APPROOT}/_debugbar/assets....`
3. in Phalcon multi module, each module should have different base URI, in my case back-end base URI is `admin`

so in back-end module, Phalcon debugger try to load assets from `{APPROOT}/admin/_debugbar/assets` url that can't be matched with phalcon debugbar assets routes.

**Comment by snowair** [comment]
@bluetec Does it work if you move these debugbar init statments from index.php to Moudule.php?

**Comment by njoyard** [comment]
@bluetec
I think you will either have to use one debugbar initialization per module (as @snowair  hinted) or use the same in all modules but then you'll need to add a way to setup debugbar baseURI as a configuration option.

**Comment by snowair** [comment]
@bluetec I had test your need. For multi module, I suggest you use Route Group Function to set route prefix for modules. The baseUri should be app global scope.

I have improved multi modules support and pushed it to the bugfix branch. 

After change your composer.json requrie to `snowair/phalcon-debugbar:dev-bugfix`, you must set your default module before start the debugbar:

```
$application->setDefaultModule('frontend');
(new \Snowair\Debugbar\ServiceProvider('../apps/debugbar.php'))->start();
```

That is all. You can try it.  If it does work,  tell me merge it to the master branch.

If the bugfix branch does not work, you can try my solution at master branch:

index.php:

```
    $di['app'] = $application;
    $manager = new  \Phalcon\Events\Manager();
    $application->setEventsManager($manager);
    $application->setDefaultModule('frontend');   // importent
    echo $application->handle()->getContent();
```

Module.php

```
    (new \Snowair\Debugbar\ServiceProvider())->start();
```
