### ISSUE TITLE
PHP Debugbar is not working

### ISSUE THREAD

**Issue by gpphong8th2** [snowair/phalcon-debugbar#18]
Hi All,
Sorry, My English is not good.
I have add phalcon-debugbar from this link: https://github.com/snowair/phalcon-debugbar.
but it is not working.
When I run, In my console is display:
![2015-10-20_162412](https://cloud.githubusercontent.com/assets/7123135/10603312/87a7d848-7747-11e5-8e2a-09765c982cbc.png)
I found error:
dashboard:449 GET http://dashboard.somo.local_debugbar/assets/stylesheets?1445331526 net::ERR_NAME_NOT_RESOLVED
dashboard:450 GET http://dashboard.somo.local_debugbar/assets/javascript?1445331525 net::ERR_NAME_NOT_RESOLVED
dashboard:453 Uncaught ReferenceError: PhpDebugBar is not defined(anonymous function) @ dashboard:453
sb-admin-2.js:2 Uncaught TypeError: $ is not a function

How to I can fix it ?

**Comment by snowair** [comment]
Config the **uri** service currectly:

```
$di->set('url', function() use (){
    $url = new Phalcon\Mvc\Url();
    $url->setBaseUri('/');  // here
    return $url;
});
```

https://github.com/snowair/phalcon-debugbar/blob/master/README_zh.md#关于-baseuri

**Comment by gpphong8th2** [comment]
thank you. But my config the uri service:
$di->set('url', function () use ($config) {
    $url = new UrlResolver();
    $url->setBaseUri($config->application->baseUri);
    return $url;
});
In config file : 'baseUri'        => 'http://dashboard.somo.local/'
I can not change 'baseUri'        => '/' . because this affects config my website.
have other solution to this issue ?

**Comment by snowair** [comment]
You should find out a way, to render the route `/_debugbar/assets/stylesheets`

from the wrong result:

```
 http://dashboard.somo.local_debugbar/assets/stylesheets
```

to the right:

```
 http://dashboard.somo.local/_debugbar/assets/stylesheets
```

**Comment by luguiant** [comment]
in phalcon simple-service-provider ind .htaccess
`
<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType text/css "access 1 month"
ExpiresByType text/html "access 1 month"
ExpiresByType application/pdf "access 1 month"
ExpiresByType text/x-javascript "access 1 month"
ExpiresByType application/x-shockwave-flash "access 1 month"
ExpiresByType image/x-icon "access 1 year"
ExpiresDefault "access plus 1 month"
</IfModule>

 <IfModule mod_rewrite.c>
    # add options
    Options -MultiViews
    RewriteEngine On
    RewriteRule ^$ public/     [L]
    RewriteRule ^((?s).*)$ public/$1 [QSA,L]

     # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>
`

and add in app\Bootstrap.php function getOutput()

`(new \Snowair\Debugbar\ServiceProvider(MYPATH.'config/debugbar.php'))->start();`

in
