### ISSUE TITLE
Magic findFirstBy methods do not work when they return null

### ISSUE THREAD

**Issue by njoyard** [snowair/phalcon-debugbar#19]
When the query does not return anything, findFirstByX fails with "method 'findFirstByX' does not exist on model 'Foo'".

This is why (`phalcon/mvc/model.zep:4036`):

``` zep
        let records = self::_invokeFinder(method, arguments);
        if records !== null {
            return records;
        }
```

`_invokeFinder` returns null both when the method name is invalid and when it is valid but actually returns null. IMO we should use exceptions here instead.

EDIT: or just return false from _invokeFinder instead?

**Comment by sergeyklay** [comment]
You aren't messed up the repo for issue? :neutral_face:

**Comment by njoyard** [comment]
Oh, yes, sorry ;)
