### ISSUE TITLE
No timeline

### ISSUE THREAD

**Issue by kamioon** [snowair/phalcon-debugbar#21]
others tab are okay, but Timeline tab is always empty? whats wrong?

<img width="1280" alt="screen shot 1394-09-13 at 9 24 20 pm" src="https://cloud.githubusercontent.com/assets/3734100/11596949/7a2a708c-9acd-11e5-950b-99624269a207.png">

**Comment by snowair** [comment]
Did you use measure method ? like this:

```
\PhalconDebug::addMeasurePoint('label1'); 
```

The debugbar does not collect any timing info by default. You should add measure code manul

**Comment by kamioon** [comment]
oh Thanks now It works.
But when i use Volt function that you listed [here](https://github.com/snowair/phalcon-debugbar#volt-functions) get errors should i add them to Volt before using it like Phalcon documentation ?

**Comment by snowair** [comment]
The debugbar has enable these volt functions. You can use it in any volt engine views. 

```
{{ addMeasurePoint( 'label' ) }}
```

**Comment by kamioon** [comment]
i put there (end of Volt page), but i get this Error:
Child templates only may contain blocks in ..... single.volt on line 50

**Comment by snowair** [comment]
put function in the template block:

```
{% extends "templates/base.volt" %}

{% block content %}
{{ addMeasurePoint( 'label' ) }}
....
{% endblock %}
```

**Comment by kamioon** [comment]
Thank you Yajie.
