### ISSUE TITLE
debugbar autoloader

### ISSUE THREAD

**Issue by jcheron** [snowair/phalcon-debugbar#27]
I have not seen how to load debugbar with Phalcon autoloader (registerDirs or registerNamespaces)
so I use composer autoloader.
This works, but is it the right solution?
The documentation says nothing about it.

What PSR specification is used?

**Comment by snowair** [comment]
it's a composer package, and it depends on other composer packages.

**Comment by jcheron** [comment]
It's not very important, because **debugbar** is a debugging tool, not for using in production.

if the other packages were PSR-4 compatible, it would be possible to respect PSR-4 specification in dedebugbar for an autoloading with Phalcon,
like that :

``` php
$loader->registerDirs(
    array(...
        $config->application->vendorDir,
    )
)->register();
```

Whatever of the autoloading method, I'll indicate it in the documentation.

**Comment by snowair** [comment]
Composer is not only just a autoloader but also a good dependences manager. It does everyting that I dose not like to do, so I choose it to be the only manager.

**Comment by jcheron** [comment]
it's your choice, and it is justified.
I will indicate explicitly the autoloading method, to prevent the Phalcon users try to do with Phalcon...

**Comment by cosmy81** [comment]
If you don't want to use the composer autoload you have to add several namespaces to your loader.php. 
    'Snowair\Debugbar' => LIB_PATH . 'vendor/snowair/phalcon-debugbar/src', //adattatore debugbar
    'DebugBar' => LIB_PATH . 'vendor/maximebf/debugbar/src/DebugBar', //debugbar sorgenti
    'Psr\Log' => LIB_PATH . 'vendor/psr/log/Psr/Log', //logger per debugbar
    'Symfony\Component\VarDumper' => LIB_PATH . 'vendor/symfony/var-dumper', //logger per debugbar
    'Symfony\Component\PolyfillMbstring' => LIB_PATH . 'vendor/symfony/Polyfill-mbstring', //logger per debugbar
