### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by al35mm** [snowair/phalcon-debugbar#29]
Not reporting any issues (yet). I just wanted to say that this is great! I have tried out fabfuel/prophiler in the past, but with my setup it doesn't work. It crashes the browser and even the server, but Phalcon Debugbar is perfect! I didn't know about it until today, and I had thrown together my own profiling bar for my current project, but your is a lot better!

Thanks

**Comment by snowair** [comment]
:smiley:
