### ISSUE TITLE
2.0.1使用Phalcon/Mvc/View/Simple报错

### ISSUE THREAD

**Issue by bug1024** [snowair/phalcon-debugbar#3]
Catchable fatal error: Argument 2 passed to Snowair\Debugbar\DataCollector\ViewCollector::__construct() must implement interface Phalcon\Mvc\ViewInterface, instance of Phalcon\Mvc\View\Simple given, called in /home/wangyu/phalcon/library/phalcon-debugbar/src/PhalconDebugbar.php on line 368 and defined in /home/wangyu/phalcon/library/phalcon-debugbar/src/DataCollector/ViewCollector.php on line 26

**Comment by snowair** [comment]
Fixed, thank you
