### ISSUE TITLE
collectors

### ISSUE THREAD

**Issue by linglingqi007** [snowair/phalcon-debugbar#30]
doctrine = true

Fatal error: Class 'Doctrine\DBAL\Logging\DebugStack' not found in /Users/huangjinlong/developer/projects/phalcon_demo/vendor/snowair/phalcon-debugbar/src/PhalconDebugbar.php on line 230

**Comment by snowair** [comment]
You should install the doctrine/orm package first.

**Comment by linglingqi007** [comment]
ok,thanks.
