### ISSUE TITLE
 Class 'Phalcon\Mvc\Vendor\Snowair\Debugbar\ServiceProvider' not found

### ISSUE THREAD

**Issue by sergioalmela** [snowair/phalcon-debugbar#31]
Hi, when I try to put your debug bar into my project, the class of Snowair is not found. This is the error:
 Class 'Phalcon\Mvc\Vendor\Snowair\Debugbar\ServiceProvider' not found in C:\xampp\htdocs\phalcon_coolmod\public\index.php on line 29
I am using Phalcon 2.0.10
My index.php:
`<?php

error_reporting(E_ALL);

define('APP_PATH', realpath('..'));

try {

```
/**
 * Read the configuration
 */
$config = include APP_PATH . "/app/config/config.php";

/**
 * Read auto-loader
 */
include APP_PATH . "/app/config/loader.php";

/**
 * Read services
 */
include APP_PATH . "/app/config/services.php";

/**
 * Handle the request
 */
$application = new \Phalcon\Mvc\Application($di);
$di['app'] = $application; //  Important
(new \Snowair\Debugbar\ServiceProvider())->start();

echo $application->handle()->getContent();
```

} catch (\Exception $e) {

}
`

I donwloaded it with composer, and is in app/vendor/snowair

**Comment by snowair** [comment]
You should include the autoload.php of composer first.
