### ISSUE TITLE
Activating collectors

### ISSUE THREAD

**Issue by metehan** [snowair/phalcon-debugbar#36]
i have added following line in public/index.php but nothing effected. What is the proper way to add collectors.

> $di['debugbar']->addCollector(new Snowair\Debugbar\DataCollector\PhalconRequestCollector);

**Comment by snowair** [comment]
You needn't add collectors by yourself. Use the config file:

https://github.com/snowair/phalcon-debugbar#use-your-config

**Comment by metehan** [comment]
Thank you. This solved my issue.
