### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by JCMais** [snowair/phalcon-debugbar#37]
From what I could see, PHP 7 support is currently blocked by third party libraries, [whoops](https://github.com/filp/whoops) and [php-debugbar](https://github.com/maximebf/php-debugbar).

For whoops, it's just needed to upgrade to v2, for php-debugbar we need to wait they add support for PHP 7: https://github.com/maximebf/php-debugbar/issues/264

**Comment by JCMais** [comment]
@snowair are you willing to accept a pull request for this issue?

**Comment by snowair** [comment]
yes
