### ISSUE TITLE
Ajax display message

### ISSUE THREAD

**Issue by galliroberto** [snowair/phalcon-debugbar#42]
i want to see a message from ajax request.
In ajax request i set a message or info to display in debugbar but it will not appeare.

how i can do that?

In debug bar I can't see ajax request.

Thanks in advantage

**Comment by snowair** [comment]
click the folder icon on the right, you will see it in the request list.

**Comment by robbygallo** [comment]
i have tried it, but nothing appear, is empty.

`'capture_ajax' => true,`

and json is correctly created (i have checked it)

`'path' => APP_PATH.'/apps/Runtime/debugbar',`

**Comment by robbygallo** [comment]
i have tried it, but nothing appear, is empty.

`'capture_ajax' => true,`

and json is correctly created (i have checked it)

`'path' => APP_PATH.'/apps/Runtime/debugbar',`

the problem is:
if i call directly http://jms-azienda.dev/_debugbar/open?max=20&offset=0
works
if i click on folder the page was not found

```
$eventsManager->attach(
        'dispatch:beforeDispatch',
        new \App\Core\Plugins\DebugBarPlugin()
    );
```

```
public function beforeDispatch(Event $event, Dispatcher $dispatcher)
    {
        /* Debugbar start */
        $ns = $dispatcher->getNamespaceName();
        // var_dump($ns); die;
        if ($ns == 'Snowair\Debugbar\Controllers') {
            return true;
        }
        /* Debugbar end */
    }
```

in ajax $ns = 'App\Frontend\Controllers'

I have multi module

**Comment by galliroberto** [comment]
ok, thanks :)

**Comment by galliroberto** [comment]
can i capture ajax request after the page is load?

e.g. when i save form in ajax with content-type application/json

**Comment by snowair** [comment]
yes

**Comment by galliroberto** [comment]
how? is always empty after form submit in ajax

**Comment by snowair** [comment]
![ajax](https://cloud.githubusercontent.com/assets/1695133/25049875/83e5449a-2176-11e7-83c9-67ece79b1751.png)
