### ISSUE TITLE
Unable to add \Throwable using the PhalconDebug helper

### ISSUE THREAD

**Issue by alexbusu** [snowair/phalcon-debugbar#52]
The method `\PhalconDebug::addException` accepts `\Exception` as argument although further are accepted Trowables as well. 
https://github.com/snowair/phalcon-debugbar/blob/master/src/Debug.php#L188 and https://github.com/snowair/phalcon-debugbar/blob/master/src/PhalconDebugbar.php#L507 

It should accept `\Throwable`, as the `\Exception` is a subclass of the former.

**Comment by snowair** [comment]
Thank you for your PR
