### ISSUE TITLE
Using doctrine with Phalcon and phalcon-debugbar

### ISSUE THREAD

**Issue by ghost** [snowair/phalcon-debugbar#8]
Hi,

I'm creating a Phalcon project, but instead of using Phalcon's native database access I'm using doctrine, since I'm more comfortable with the data-mapper pattern rather than the active record one.

Anyway, I'm using your awesome phalcon-debugbar but I'm not able to see database information.

I went to the original [PHP Debug Bar documentation](http://phpdebugbar.com/docs/bridge-collectors.html) to look for a solution, but it doesn't seem to work. 

What I did was, following the mentioned docs and your instructions, to insert this lines of code in my bootstrap:

``` php
        $application = new Phalcon\Mvc\Application($di);
        // CONFIGURE DEBUGBAR
        $di['app'] = $application;
        (new ServiceProvider(APP_PATH . 'config/debugbar.php'))->start();
        $em = $di->get('entityManager');
        $debugStack = new DebugStack();
        $em->getConnection()->getConfiguration()->setSQLLogger($debugStack);
        $debugbar = $di->get('debugbar');
        $debugbar->addCollector(new DoctrineCollector($debugStack));
        echo $application->handle()->getContent();
```

Is there any way that I can manage to see the database tab using doctrine in Phalcon?

Thanks for the awesome job, and thanks in advance for your help

**Comment by snowair** [comment]
Sorry, phalcon debugbar only support the Phalcon ORM for now.

**Comment by snowair** [comment]
Now, I had add DoctrineCollector support in v1.1.18, you can try it.

Edit debugbar config , set "doctrine" to "true".  Then It will auto collect infomations from "entityManager" service.

**Comment by ghost** [comment]
That's great! I'll try it ASAP

On Sun, Sep 13, 2015 at 4:45 PM, Yajie Zhu notifications@github.com wrote:

> Now, I had add DoctrineCollector support in v1.1.18, you can try it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/snowair/phalcon-debugbar/issues/8#issuecomment-139883241
> .

## 

## 

Antonio Hernández

**Comment by ghost** [comment]
Works like a charm. Thank you very much!
