### ISSUE TITLE
phalcon-module-skeleton integration

### ISSUE THREAD

**Issue by Izopi4a** [snowair/phalcon-debugbar#9]
hello,

can you help me with "how to" integrade your debugger into this application, since it's started in a different way

https://github.com/ovr/phalcon-module-skeleton

i get hte fllowing error:

Fatal error: Uncaught exception 'Phalcon\Di\Exception' with message 'A dependency injection object is required to access the application services' in phalcon/di/injectable.zep:127

**Comment by snowair** [comment]
```
$application = new \Phalcony\Application(APPLICATION_ENV, $config);
$application->bootstrap();
$di = \Phalcon\Di::getDefault();
$di['app'] = $application;
(new Snowair\Debugbar\ServiceProvider())->start();
$application->run();
```

If it works, please help more pepole know how to do it. Thanks.
